# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

#theme                    : "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.16.0"
#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "N-HUM-INNO"
title_separator          : "|"
name                     : "N-HUM-INNO LabCom"
description              : "N-HUM-INNO LabCom"
#url                      : #"https://erpi.univ-lorraine.fr"
baseurl                  : # the subpath of your site, e.g. "/blog"
url                      : "https://n-hum-inno.eu"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "gaarbelaez/n-hum-inno" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment."
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : false #, false (default)
search_full_content      : false #, false (default)
search_provider          : # lunr (default), algolia
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false

# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# Site Author
author:
  name             : "ERPI Team"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : ""
  location         : "Worldwide"
  email            :
  uri              : ""
  home             : # null (default), "absolute or relative url to link to author home"
  flickr           :
  facebook         :
  github           : 
  lastfm           :
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: #/:categories/:title/
paginate: #5 # amount of posts to show
paginate_path: #/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
    
# Languages

languages:
  - 
    - 
    - English
  - 
    - fr
    - Français


# Directories
collections_dir: collections
layouts_dir: _jekyll/_layouts
includes_dir: _jekyll/_includes

# Collections
collections:  
  posts:
    output: true
    permalink: /:collection/:year/:title/

  publications:
    output: true
    permalink: /:path    
  projects:
    output: true    
  people:
    output: true
    permalink: /:collection/:path/
  summer-school:
    output: true




# Defaults

defaults:

  # default
  - scope:
      path: ""
    values:
      lang: en
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      
  
  # _POST Folder
  - scope:
      type: posts
    values:
      layout: single
      is_post: true
      share: true
      read_time: true
      related: false
      
    # en
  - scope:
      path: "_posts/en"
    values:
      lang: en

    # fr
  - scope:
      path: "_posts/fr"
    values:
      lang: fr           
      permalink: /fr/:collection/:year/:title/

  # _pages Main Pages of the site
  - scope:
      type: pages
    values:
      sidebar: 
        nav: ""
    # en
  - scope:
      path: "_pages/en"
    values:
      lang: en
      layout: single
      header:
        overlay_filter: 0.3
        show_overlay_excerpt: true 
    # de
  - scope:
      path: "_pages/fr"
    values:
      lang: fr
      layout: single
      header:
        overlay_filter: 0.3
        show_overlay_excerpt: true 



  # _publications
  - scope:
      type: publications
    values:      
      sidebar:
        nav: ""      
    #en
  - scope:
      path: "_publications/en"
    values:
      lang: en
      sidebar:
        nav: "publications"      

    #fr
  - scope:
      path: "_publications/fr"
    values:
      lang: fr          
      sidebar:
        nav: "publications"    


  # _projects
  - scope:
      type: projects
    values:
      layout: single
      header:
        overlay_filter: 0.4
        show_overlay_excerpt: true 
      sidebar:
        nav: ""      
    #en
  - scope:
      path: "_projects/en"
    values:
      lang: en
      permalink: /:collection/:title/
      sidebar:
        nav: "projects"        
    #fr
  - scope:
      path: "_projects/fr"
    values:
      lang: fr
      permalink: /fr/:collection/:title/
      sidebar:
        nav: "projects"        


# _people
  - scope:
      type: people
    values:
      layout: single
      author_profile: true
      
    #en
  - scope:
      path: "_people/en"
    values:
      lang: en
    #fr
  - scope:
      path: "_people/fr"
    values:
      lang: fr



# It'd be nice to have "lang" set through wildcard, using * for directories:
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# this doesn't seem to work
# e.g.:
#  - scope:
#      path: "*/de"
#    values:
#      lang: de  

  


